steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/reportes-conduccion-backend:latest', '.']

# 2. Push the container image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/reportes-conduccion-backend:latest']

# 3. Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'reportes-conduccion-backend-v2' # <-- Desplegando como un servicio nuevo
  - '--image'
  - 'gcr.io/$PROJECT_ID/reportes-conduccion-backend:latest'
  - '--region'
  - 'us-central1'
  - '--set-env-vars'
  - 'DEBUG=false,ENVIRONMENT=production'
  - '--clear-secrets' # Limpia cualquier configuración de secretos anterior

images:
- 'gcr.io/$PROJECT_ID/reportes-conduccion-backend:latest'
